{
 "title": "Grommunio",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "tenant",
    "query": {
     "query": "label_values(grommunio_mailbox_count,__tenant_id__)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(grommunio_mailbox_count,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Grommunio Mailbox Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grommunio_mailbox_count{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Grommunio Shared Mailbox Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "grommunio_shared_mailbox_count{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Grommunio Mailbox Sizes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Grommunio Mailbox Used Storage Quota %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-((grommunio_mailbox_storage_quota_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\"} - grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})/grommunio_mailbox_storage_quota_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Grommunio Mailbox Used Prohibit Receive Quota %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-((grommunio_mailbox_prohibit_receive_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\"} - grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})/grommunio_mailbox_prohibit_receive_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Grommunio Mailbox Used Prohibit Receive Quota %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-((grommunio_mailbox_prohibit_send_quota{__tenant_id__=~\"$tenant\",instance=~\"$instance\"} - grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})/grommunio_mailbox_prohibit_send_quota{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Grommunio Mailbox Creation date",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "grommunio_mailbox_creation_time{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}