{
 "title": "Grommunio 20250910",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "tenant",
    "query": {
     "query": "label_values(grommunio_mailbox_count,__tenant_id__)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(grommunio_mailbox_count{__tenant_id__=~\"$tenant\"},instance)"
    }
   },
   {
    "name": "domain",
    "label": "domain",
    "query": {
     "query": "label_values(grommunio_mailbox_messagesize{instance=~\"$instance\"},domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grommunio_api_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "grommunio_exporter_version{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "grommunio_admin_version{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "grommunio_gromox_version{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mailbox Count per domain",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "grommunio_mailbox_count{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Total Mailbox Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (grommunio_mailbox_count{__tenant_id__=~\"$tenant\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Shared Mailbox Count per domain",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "grommunio_shared_mailbox_count{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Mailbox Sizes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Mailbox Used Storage Quota %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-((grommunio_mailbox_storage_quota_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"} - grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"})/grommunio_mailbox_storage_quota_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Mailbox Used Prohibit Receive Quota %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-((grommunio_mailbox_prohibit_receive_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"} - grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"})/grommunio_mailbox_prohibit_receive_limit{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Mailbox Used Prohibit Send Quota %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-((grommunio_mailbox_prohibit_send_quota{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"} - grommunio_mailbox_messagesize{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"})/grommunio_mailbox_prohibit_send_quota{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Mailbox Creation date",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "grommunio_mailbox_creation_time{__tenant_id__=~\"$tenant\",instance=~\"$instance\",domain=~\"$domain\"}",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}